storage:
  documents_path: ./data/documents
  vector_db_path: ./data/chromadb
  model_cache_path: ~/.cache/huggingface

embedding:
  model_name: sentence-transformers/all-MiniLM-L6-v2
  batch_size: 32
  device: cpu

chunking:
  chunk_size: 500
  chunk_overlap: 50
  strategy: sentence

processing:
  max_concurrent_tasks: 3
  ocr_confidence_threshold: 0.6
  max_file_size_mb: 100

mcp:
  host: 0.0.0.0
  port: 3000
  transport: http
